name: cobacoba
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  intl_phone_field: ^3.1.0
  font_awesome_flutter: ^10.4.0
  dotted_border: ^2.0.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.14
  file_picker: ^10.1.2
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Baju.jpg
    - assets/AiDorseLogo.png
    - assets/default_qr.png
    - assets/icons/youtube.jpg
    - assets/icons/instagram.png
    - assets/icons/tiktok.png
    - assets/file/agreement.pdf
    - assets/login_regist/devicon_google.svg
    - assets/login_regist/pembatas.svg

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
